source :rubygems

# Use bson_ext for speed improvements:
gem 'bson_ext', '~> 1.0.7'

# This example app needs some gems not provided by sinatra_resource:
gem 'rack-test', '~> 0.5.4'

# Don't use the following line in your sinatra_resource application...
gemspec :path => '../..'
# ...instead use:
# gem 'sinatra_resource', '~> 0.4.23'
# (use the latest version, not necessarily 0.4.23)
